# Generated by Django 4.1.2 on 2023-01-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_app_otp_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
