# Generated by Django 4.1.2 on 2023-01-11 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="null", max_length=20)),
                ("detail", models.TextField(default="null")),
                ("status", models.BooleanField(default=False)),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
