# Generated by Django 4.1.2 on 2023-01-11 15:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0003_alter_app_status"),
        ("blog", "0001_initial"),
        ("service", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auth_code", models.TextField(default="null")),
                ("name", models.CharField(default="null", max_length=50)),
                ("category", models.CharField(default="null", max_length=50)),
                ("location", models.CharField(default="null", max_length=50)),
                ("bio", models.CharField(default="null", max_length=50)),
                ("email", models.CharField(default="null", max_length=50)),
                ("phone", models.CharField(default="null", max_length=50)),
                ("address", models.TextField(default="null")),
                ("status", models.BooleanField(default=False)),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "app_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.app"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessServiceConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.business",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessProductConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.business",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessBlogConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.blog"
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.business",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="business",
            name="blogs",
            field=models.ManyToManyField(
                through="business.BusinessBlogConnector", to="blog.blog"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="products",
            field=models.ManyToManyField(
                through="business.BusinessProductConnector", to="product.product"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="services",
            field=models.ManyToManyField(
                through="business.BusinessServiceConnector", to="service.service"
            ),
        ),
    ]
